---
- hosts: all
  tasks:
    - name: Install packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - cifs-utils
        - ctags
        - byobu
        - git
        - vim
        - psmisc
        - htop
      tags:
        - packages

    - name: Append Vi setting to ~/.inputrc (GNU Readline)
      lineinfile:
        path: "{{ ansible_env.HOME  + '/.inputrc' }}"
        insertafter: EOF
        state: present
        create: yes
        line: "set editing-mode vi"

    - name: Append Vi setting to ~/.bashrc
      lineinfile:
        path: "{{ ansible_env.HOME  + '/.bashrc' }}"
        insertafter: EOF
        line: "set -o vi"

    - name: Create the directory for vim-plug
      file:
        path: "{{ ansible_env.HOME + '/.vim/autoload/' }}"
        state: directory

    - name: Download vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME + '/.vim/autoload/' }}"

    - name: Create the directory for the vim plugins
      file:
        path: "{{ ansible_env.HOME + '/.vim/plugged/' }}"
        state: directory

    - name: Copy the plugin vimrc
      copy:
        src: vimrc.d/00-vimrc.plugins
        dest: "{{ ansible_env.HOME + '/.vimrc.plugins' }}"

    - name: Run vim to install the plugins
      command: vim -u "{{ ansible_env.HOME + '/.vimrc.plugins' }}" +PlugInstall +qall

    - name: Assemble the vimrc
      assemble:
        src: vimrc.d
        dest: "{{ ansible_env.HOME + '/.vimrc' }}"

    - name: Download terminal colours for solarized dark theme
      get_url:
        url: https://raw.githubusercontent.com/mavnn/mintty-colors-solarized/master/sol.dark
        dest: "{{ ansible_env.HOME + '/.sol.dark' }}"
        
    - name: Append colourscheme setting to ~/.bashrc
      lineinfile:
        path: "{{ ansible_env.HOME  + '/.bashrc' }}"
        insertafter: EOF
        line: "source ~/.sol.dark"

